2021-12-20 18:51:02,262 DEBUG    root            Loaded Command Group: ['gcloud', 'sql']
2021-12-20 18:51:02,264 DEBUG    root            Loaded Command Group: ['gcloud', 'sql', 'instances']
2021-12-20 18:51:02,280 DEBUG    root            Loaded Command Group: ['gcloud', 'sql', 'instances', 'list']
2021-12-20 18:51:02,288 DEBUG    root            Running [gcloud.sql.instances.list] with arguments: []
2021-12-20 18:51:02,300 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/712862630822-compute@developer.gserviceaccount.com/?recursive=true
2021-12-20 18:51:02,302 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-12-20 18:51:02,304 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/712862630822-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 207
2021-12-20 18:51:02,305 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/712862630822-compute@developer.gserviceaccount.com/token
2021-12-20 18:51:02,307 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/712862630822-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 269
2021-12-20 18:51:02,336 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/712862630822-compute@developer.gserviceaccount.com/?recursive=true
2021-12-20 18:51:02,338 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-12-20 18:51:02,340 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/712862630822-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 207
2021-12-20 18:51:02,340 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/712862630822-compute@developer.gserviceaccount.com/token
2021-12-20 18:51:02,342 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/712862630822-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 269
2021-12-20 18:51:02,352 INFO     root            Display format: ":(settings.userLabels:alias=labels:label=LABELS) table(name,databaseVersion,firstof(gceZone,region):label=LOCATION,settings.tier,ip_addresses.filter("type:PRIMARY").*extract(ip_address).flatten().yesno(no="-"):label=PRIMARY_ADDRESS,ip_addresses.filter("type:PRIVATE").*extract(ip_address).flatten().yesno(no="-"):label=PRIVATE_ADDRESS,state:label=STATUS)"
2021-12-20 18:51:02,354 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): sqladmin.googleapis.com:443
2021-12-20 18:51:02,395 DEBUG    urllib3.connectionpool https://sqladmin.googleapis.com:443 "GET /sql/v1beta4/projects/analog-bot-325915/instances?alt=json&maxResults=100 HTTP/1.1" 403 None
2021-12-20 18:51:03,407 DEBUG    root            (gcloud.sql.instances.list) User [712862630822-compute@developer.gserviceaccount.com] does not have permission to access projects instance [analog-bot-325915] (or it may not exist): Cloud SQL Admin API has not been used in project 712862630822 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=712862630822 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=712862630822
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/712862630822
    service: sqladmin.googleapis.com
  reason: SERVICE_DISABLED
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 811, in Run
    display_info=self.ai.display_info).Display()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 483, in Display
    self._printer.Print(self._resources)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 297, in Print
    for resource in resources:
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/sql/instances.py", line 236, in YieldInstancesWithAModifiedState
    for result in yielded:
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/list_pager.py", line 121, in YieldFromList
    global_params=global_params)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/sqladmin/v1beta4/sqladmin_v1beta4_client.py", line 687, in List
    config, request, global_params=global_params)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 735, in _RunMethod
    http, http_request, **opts)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 360, in MakeRequest
    max_retry_wait, total_wait_sec))
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 350, in MakeRequest
    check_response_func=check_response_func)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 406, in _MakeRequestNoRetry
    check_response_func(response)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 242, in _CheckResponseForApiEnablement
    PromptToEnableApi(*enablement_info)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 209, in PromptToEnableApi
    raise exception
googlecloudsdk.api_lib.util.exceptions.HttpException: User [712862630822-compute@developer.gserviceaccount.com] does not have permission to access projects instance [analog-bot-325915] (or it may not exist): Cloud SQL Admin API has not been used in project 712862630822 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=712862630822 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=712862630822
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/712862630822
    service: sqladmin.googleapis.com
  reason: SERVICE_DISABLED
2021-12-20 18:51:03,411 ERROR    root            (gcloud.sql.instances.list) User [712862630822-compute@developer.gserviceaccount.com] does not have permission to access projects instance [analog-bot-325915] (or it may not exist): Cloud SQL Admin API has not been used in project 712862630822 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=712862630822 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=712862630822
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/712862630822
    service: sqladmin.googleapis.com
  reason: SERVICE_DISABLED
